### api base
GET http://localhost:8000/

### api qa
POST http://localhost:8000/jb14/qa
Content-Type: text/plain

고창

### prompt api test
POST http://localhost:8000/jb14/prompt
Content-Type: text/plain

임실

### streaming api test
POST http://localhost:8000/jb14/qa_stream
Content-Type: application/json

고창